name: Pull requests check

on:
  push:
    branches:
      - master

jobs:
  check-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install --package-lock-only
      - run: npm ci
      - run: npm run build:prod
  deploy:
    needs: check-build
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ~/.ssh/
      - run: echo "${{ secrets.STAGING_SSH_PRIVATE_KEY }}" > ~/.ssh/private.key
      - run: chmod 600 ~/.ssh/private.key
      - run: ssh -i ~/.ssh/private.key -o "StrictHostKeyChecking no" root@af8a7307a82e.vps.myjino.ru -p 49215 whoami
      - run: pwd
